title: John Doe # your name (or website title) here
logo: "/images/IMG_9964.JPG" # your photo (or logo) here
description: > # your text below (remove <br> elements if you don't need line breaks)
  Starting Journey As a Data Analyst
  <br><br>
  Excited to learn more SQL, Python and Coding
  <br><br>
  <a href="https://www.linkedin.com/in/example/">View My LinkedIn Profile</a> 
  
theme: jekyll-theme-minimal
google_analytics: UA-000000-0 # your Google Analytics tracking ID here
